plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
env:
  browser: true
  es2021: true
extends: 
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
   'linebreak-style': ["error", "windows"]
   import/extensions:
    - error
    - ignorePackages
    - js: always
   no-console: 0
   
